/**
 * Export utilities: PDF and Markdown
 */
import type { GraphState } from '@/lib/langgraph/state';
import { formatCurrency, formatPercent } from './formatters';

export function exportToMarkdown(result: GraphState): void {
  const rec = result.recommendation ?? 'WATCH';
  const scores = result.scores;
  const profile = result.companyProfile;

  const lines: string[] = [
    `# Investment Research Report: ${profile?.name ?? result.company}`,
    '',
    `> Generated by AI Investment Research Agent | ${new Date().toLocaleDateString()}`,
    '',
    '---',
    '',
    '## Investment Recommendation',
    '',
    `**Recommendation:** ${rec}`,
    '',
    scores
      ? `| Metric | Score |
|--------|-------|
| Investment Score | ${scores.investment}/100 |
| Financial Health | ${scores.financialHealth}/100 |
| Safety (Risk) | ${scores.riskScore}/100 |
| Growth | ${scores.growthScore}/100 |
| Confidence | ${scores.confidence}/100 |`
      : '',
    '',
    '---',
    '',
    '## Executive Summary',
    '',
    result.summary ?? '_No summary available_',
    '',
    '---',
    '',
    '## Company Overview',
    '',
    profile
      ? `- **Symbol:** ${profile.symbol}
- **Industry:** ${profile.industry ?? 'N/A'}
- **Market Cap:** ${formatCurrency(profile.marketCap)}
- **Stock Price:** ${profile.currentPrice ? `$${profile.currentPrice.toFixed(2)}` : 'N/A'}
- **Exchange:** ${profile.exchange ?? 'N/A'}
- **Country:** ${profile.country ?? 'N/A'}`
      : '_Company profile unavailable_',
    '',
    '---',
    '',
    '## SWOT Analysis',
    '',
    result.swot
      ? `### Strengths\n${result.swot.strengths.map((s) => `- ${s}`).join('\n')}\n\n### Weaknesses\n${result.swot.weaknesses.map((s) => `- ${s}`).join('\n')}\n\n### Opportunities\n${result.swot.opportunities.map((s) => `- ${s}`).join('\n')}\n\n### Threats\n${result.swot.threats.map((s) => `- ${s}`).join('\n')}`
      : '_SWOT analysis unavailable_',
    '',
    '---',
    '',
    '## Risk Analysis',
    '',
    result.risks.length > 0
      ? result.risks.map((r) => `### ${r.category}\n**Level:** ${r.level.toUpperCase()}\n${r.description}`).join('\n\n')
      : '_Risk analysis unavailable_',
    '',
    '---',
    '',
    '## Growth Analysis',
    '',
    result.growthFactors.length > 0
      ? result.growthFactors.map((g) => `### ${g.category}\n**Impact:** ${g.impact.toUpperCase()}\n${g.description}`).join('\n\n')
      : '_Growth analysis unavailable_',
    '',
    '---',
    '',
    '## AI Analyst Reasoning',
    '',
    result.reasoning ?? '_Reasoning unavailable_',
    '',
    '---',
    '',
    '## Recent News',
    '',
    result.news.length > 0
      ? result.news.slice(0, 5).map((n) => `- **[${n.title}](${n.url})** _(${n.source}, ${n.publishedAt.split('T')[0]})_ — ${n.sentiment?.toUpperCase() ?? ''}`)
          .join('\n')
      : '_No news available_',
    '',
    '---',
    '',
    '> ⚠️ This report is AI-generated for research purposes only. Not financial advice.',
  ];

  const markdown = lines.join('\n');
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${(profile?.name ?? result.company).replace(/\s+/g, '_')}_investment_report.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function exportToPDF(): Promise<void> {
  try {
    const { default: html2canvas } = await import('html2canvas');
    const { default: jsPDF } = await import('jspdf');

    const element = document.getElementById('results-dashboard');
    if (!element) {
      alert('Could not find report content to export.');
      return;
    }

    const canvas = await html2canvas(element, {
      scale: 1.5,
      backgroundColor: '#050b14',
      useCORS: true,
      logging: false,
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = pageWidth;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    let y = 0;
    while (y < imgHeight) {
      if (y > 0) pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, -y, imgWidth, imgHeight);
      y += pageHeight;
    }

    pdf.save(`investment_report.pdf`);
  } catch (err) {
    console.error('PDF export failed:', err);
    alert('PDF export failed. Try the Markdown export instead.');
  }
}
