'use client';

import type { Scores } from '@/types/recommendation';
import { AlertTriangle, CheckCircle, Info } from 'lucide-react';

interface ReasoningCardProps {
  reasoning?: string;
  summary?: string;
  scores?: Scores;
  errors: string[];
}

export default function ReasoningCard({ reasoning, summary, scores, errors }: ReasoningCardProps) {
  return (
    <div className="card">
      <h2 style={{ fontSize: '16px', fontWeight: 600, marginBottom: '16px' }}>
        AI Analyst Reasoning & Disclosures
      </h2>

      {/* Executive Summary */}
      {summary && (
        <div
          style={{
            padding: '14px 16px',
            borderRadius: '6px',
            background: 'var(--bg-surface)',
            border: '1px solid var(--border)',
            marginBottom: '16px',
            display: 'flex',
            gap: '10px',
            alignItems: 'flex-start',
          }}
        >
          <Info size={14} style={{ color: 'var(--brand-light)', flexShrink: 0, marginTop: '2px' }} />
          <div>
            <div style={{ fontSize: '11px', fontWeight: 600, color: 'var(--text-primary)', marginBottom: '4px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
              Executive Summary
            </div>
            <p style={{ margin: 0, fontSize: '13px', color: 'var(--text-secondary)', lineHeight: '1.5' }}>
              {summary}
            </p>
          </div>
        </div>
      )}

      {/* Detailed reasoning */}
      {reasoning ? (
        <div
          style={{
            fontSize: '13px',
            color: 'var(--text-secondary)',
            lineHeight: '1.6',
            whiteSpace: 'pre-wrap',
            padding: '16px',
            borderRadius: '6px',
            background: 'var(--bg-surface)',
            border: '1px solid var(--border)',
            marginBottom: errors.length > 0 ? '12px' : 0,
          }}
        >
          {reasoning}
        </div>
      ) : (
        <p style={{ color: 'var(--text-muted)', fontSize: '13px' }}>
          Detailed AI reasoning unavailable.
        </p>
      )}

      {/* Confidence status */}
      {scores && (
        <div
          style={{
            marginTop: '12px',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            padding: '8px 12px',
            borderRadius: '4px',
            background: 'var(--bg-surface)',
            border: '1px solid var(--border)',
          }}
        >
          <CheckCircle size={13} style={{ color: 'var(--success)' }} />
          <span style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>
            Analysis confidence score:{' '}
            <strong style={{ color: 'var(--text-primary)', fontFamily: 'var(--font-mono)' }}>{scores.confidence}%</strong>
            {scores.confidence < 60 && (
              <span style={{ color: 'var(--warning)', marginLeft: '8px' }}>
                (limited data available — results might be partial)
              </span>
            )}
          </span>
        </div>
      )}

      {/* Warnings */}
      {errors.length > 0 && (
        <div
          style={{
            marginTop: '12px',
            padding: '10px 14px',
            borderRadius: '6px',
            background: 'rgba(245,158,11,0.02)',
            border: '1px solid rgba(245,158,11,0.15)',
          }}
        >
          <div style={{ display: 'flex', gap: '6px', alignItems: 'center', marginBottom: '6px' }}>
            <AlertTriangle size={13} style={{ color: 'var(--warning)' }} />
            <span style={{ fontSize: '11px', fontWeight: 600, color: 'var(--warning)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
              System Disclosures ({errors.length})
            </span>
          </div>
          <ul style={{ margin: 0, padding: '0 0 0 14px', display: 'flex', flexDirection: 'column', gap: '4px' }}>
            {errors.map((err, i) => (
              <li key={i} style={{ fontSize: '11px', color: 'var(--text-muted)' }}>{err}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Disclaimer */}
      <p
        style={{
          marginTop: '16px',
          fontSize: '10px',
          color: 'var(--text-muted)',
          lineHeight: '1.4',
          borderTop: '1px solid var(--border)',
          paddingTop: '8px',
        }}
      >
        DISCLAIMER: This report is generated by a automated AI pipeline for informational and educational purposes only. It does not constitute investment advice, financial planning, or a recommendation to buy or sell any security. Market investments carry substantial risk.
      </p>
    </div>
  );
}
